/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_mainwindow (void)
{
  GtkWidget *mainwindow;
  GtkWidget *vbox1;
  GtkWidget *toolbar1;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *button_gallery_open;
  GtkWidget *button_gallery_save;
  GtkWidget *button_gallery_make;
  GtkWidget *button_gallery_stop;
  GtkWidget *button_gallery_configure;
  GtkWidget *toolitem1;
  GtkWidget *vseparator1;
  GtkWidget *button_image_add;
  GtkWidget *button_image_remove;
  GtkWidget *toolitem2;
  GtkWidget *vseparator2;
  GtkWidget *button_pwg_preferences;
  GtkWidget *button_pwg_quit;
  GtkWidget *button_pwg_about;
  GtkWidget *hpaned1;
  GtkWidget *vbox2;
  GtkWidget *button_move_top;
  GtkWidget *alignment5;
  GtkWidget *hbox6;
  GtkWidget *image4;
  GtkWidget *label8;
  GtkWidget *button_move_up;
  GtkWidget *alignment3;
  GtkWidget *hbox4;
  GtkWidget *image2;
  GtkWidget *label6;
  GtkWidget *scrolledwindow_thumb;
  GtkWidget *table_thumb;
  GtkWidget *button_move_down;
  GtkWidget *alignment4;
  GtkWidget *hbox5;
  GtkWidget *image3;
  GtkWidget *label7;
  GtkWidget *button_move_bottom;
  GtkWidget *alignment6;
  GtkWidget *hbox7;
  GtkWidget *image5;
  GtkWidget *label9;
  GtkWidget *vbox3;
  GtkWidget *progressbar_status;
  GtkWidget *label_filename;
  GtkWidget *hbox1;
  GtkWidget *frame1;
  GtkWidget *alignment1;
  GtkWidget *scrolledwindow1;
  GtkWidget *textview_description;
  GtkWidget *label2;
  GtkWidget *frame2;
  GtkWidget *alignment2;
  GtkWidget *vbox4;
  GtkWidget *check_settings_nomodify;
  GtkWidget *hbox2;
  GtkWidget *label3;
  GtkWidget *scale_settings_gamma;
  GtkWidget *hbox3;
  GtkWidget *label4;
  GtkWidget *scale_settings_rotate;
  GtkWidget *label5;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  mainwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (mainwindow), _("pwgallery"));
  gtk_window_set_default_size (GTK_WINDOW (mainwindow), 800, 600);

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (mainwindow), vbox1);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_box_pack_start (GTK_BOX (vbox1), toolbar1, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1));

  tmp_image = gtk_image_new_from_stock ("gtk-open", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_gallery_open = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Open"));
  gtk_widget_show (button_gallery_open);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_gallery_open);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_gallery_open), tooltips, _("Open gallery"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-save", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_gallery_save = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Save"));
  gtk_widget_show (button_gallery_save);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_gallery_save);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_gallery_save), tooltips, _("Save gallery"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-media-play", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_gallery_make = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Make"));
  gtk_widget_show (button_gallery_make);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_gallery_make);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_gallery_make), tooltips, _("Make gallery"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-media-stop", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_gallery_stop = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Stop"));
  gtk_widget_show (button_gallery_stop);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_gallery_stop);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_gallery_stop), tooltips, _("Stop making gallery"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-properties", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_gallery_configure = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Configure"));
  gtk_widget_show (button_gallery_configure);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_gallery_configure);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_gallery_configure), tooltips, _("Configure gallery"), NULL);

  toolitem1 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem1);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem1);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_container_add (GTK_CONTAINER (toolitem1), vseparator1);

  tmp_image = gtk_image_new_from_stock ("gtk-add", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_image_add = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Add"));
  gtk_widget_show (button_image_add);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_image_add);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_image_add), tooltips, _("Add images to gallery"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-remove", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_image_remove = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Remove"));
  gtk_widget_show (button_image_remove);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_image_remove);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_image_remove), tooltips, _("Remove selected image from gallery"), NULL);

  toolitem2 = (GtkWidget*) gtk_tool_item_new ();
  gtk_widget_show (toolitem2);
  gtk_container_add (GTK_CONTAINER (toolbar1), toolitem2);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_container_add (GTK_CONTAINER (toolitem2), vseparator2);

  tmp_image = gtk_image_new_from_stock ("gtk-preferences", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_pwg_preferences = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Preferences"));
  gtk_widget_show (button_pwg_preferences);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_pwg_preferences);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_pwg_preferences), tooltips, _("PWGallery preferences"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-quit", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_pwg_quit = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Quit"));
  gtk_widget_show (button_pwg_quit);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_pwg_quit);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_pwg_quit), tooltips, _("Quit PWGallery"), NULL);

  button_pwg_about = (GtkWidget*) gtk_tool_button_new_from_stock ("gtk-about");
  gtk_widget_show (button_pwg_about);
  gtk_container_add (GTK_CONTAINER (toolbar1), button_pwg_about);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_pwg_about), tooltips, _("About PWGallery"), NULL);

  hpaned1 = gtk_hpaned_new ();
  gtk_widget_show (hpaned1);
  gtk_box_pack_start (GTK_BOX (vbox1), hpaned1, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (hpaned1), 200);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox2);
  gtk_paned_pack1 (GTK_PANED (hpaned1), vbox2, FALSE, TRUE);

  button_move_top = gtk_button_new ();
  gtk_widget_show (button_move_top);
  gtk_box_pack_start (GTK_BOX (vbox2), button_move_top, FALSE, FALSE, 0);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (button_move_top), alignment5);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox6);

  image4 = gtk_image_new_from_stock ("gtk-goto-top", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox6), image4, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Move top"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox6), label8, FALSE, FALSE, 0);

  button_move_up = gtk_button_new ();
  gtk_widget_show (button_move_up);
  gtk_box_pack_start (GTK_BOX (vbox2), button_move_up, FALSE, FALSE, 0);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (button_move_up), alignment3);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox4);

  image2 = gtk_image_new_from_stock ("gtk-go-up", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox4), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Move up"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox4), label6, FALSE, FALSE, 0);

  scrolledwindow_thumb = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow_thumb);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow_thumb, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow_thumb), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  table_thumb = gtk_table_new (1, 1, TRUE);
  gtk_widget_show (table_thumb);
  gtk_container_add (GTK_CONTAINER (scrolledwindow_thumb), table_thumb);

  button_move_down = gtk_button_new ();
  gtk_widget_show (button_move_down);
  gtk_box_pack_start (GTK_BOX (vbox2), button_move_down, FALSE, FALSE, 0);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (button_move_down), alignment4);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox5);

  image3 = gtk_image_new_from_stock ("gtk-go-down", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox5), image3, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Move down"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);

  button_move_bottom = gtk_button_new ();
  gtk_widget_show (button_move_bottom);
  gtk_box_pack_start (GTK_BOX (vbox2), button_move_bottom, FALSE, FALSE, 0);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (button_move_bottom), alignment6);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox7);

  image5 = gtk_image_new_from_stock ("gtk-goto-bottom", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox7), image5, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Move bottom"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox7), label9, FALSE, FALSE, 0);

  vbox3 = gtk_vbox_new (FALSE, 10);
  gtk_widget_show (vbox3);
  gtk_paned_pack2 (GTK_PANED (hpaned1), vbox3, TRUE, TRUE);

  progressbar_status = gtk_progress_bar_new ();
  gtk_widget_show (progressbar_status);
  gtk_box_pack_start (GTK_BOX (vbox3), progressbar_status, FALSE, FALSE, 0);
  gtk_progress_bar_set_text (GTK_PROGRESS_BAR (progressbar_status), _("Idle"));

  label_filename = gtk_label_new (_("/path/to/filename"));
  gtk_widget_show (label_filename);
  gtk_box_pack_start (GTK_BOX (vbox3), label_filename, FALSE, FALSE, 0);

  hbox1 = gtk_hbox_new (TRUE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox3), hbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (NULL);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox1), frame1, FALSE, TRUE, 0);

  alignment1 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (frame1), alignment1);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment1), 0, 0, 12, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (alignment1), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_SHADOW_IN);

  textview_description = gtk_text_view_new ();
  gtk_widget_show (textview_description);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), textview_description);
  gtk_text_buffer_set_text (gtk_text_view_get_buffer (GTK_TEXT_VIEW (textview_description)), _("Insert text here. \n\nUsing html tags is allowed."), -1);

  label2 = gtk_label_new (_("<b>Description</b>"));
  gtk_widget_show (label2);
  gtk_frame_set_label_widget (GTK_FRAME (frame1), label2);
  gtk_label_set_use_markup (GTK_LABEL (label2), TRUE);

  frame2 = gtk_frame_new (NULL);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (vbox3), frame2, FALSE, TRUE, 0);

  alignment2 = gtk_alignment_new (0.5, 0.5, 1, 1);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (frame2), alignment2);
  gtk_alignment_set_padding (GTK_ALIGNMENT (alignment2), 0, 0, 12, 0);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox4);
  gtk_container_add (GTK_CONTAINER (alignment2), vbox4);
  gtk_container_set_border_width (GTK_CONTAINER (vbox4), 5);

  check_settings_nomodify = gtk_check_button_new_with_mnemonic (_("Do not modify original image"));
  gtk_widget_show (check_settings_nomodify);
  gtk_box_pack_start (GTK_BOX (vbox4), check_settings_nomodify, FALSE, FALSE, 0);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox2, TRUE, TRUE, 0);

  label3 = gtk_label_new (_("Gamma:"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox2), label3, FALSE, FALSE, 0);

  scale_settings_gamma = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (1, 0.1, 10, 0.1, 1, 1)));
  gtk_widget_show (scale_settings_gamma);
  gtk_box_pack_start (GTK_BOX (hbox2), scale_settings_gamma, TRUE, TRUE, 0);
  gtk_scale_set_value_pos (GTK_SCALE (scale_settings_gamma), GTK_POS_LEFT);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox3, TRUE, TRUE, 0);

  label4 = gtk_label_new (_("Rotate:"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox3), label4, FALSE, FALSE, 0);

  scale_settings_rotate = gtk_hscale_new (GTK_ADJUSTMENT (gtk_adjustment_new (0, 0, 360, 1, 30, 30)));
  gtk_widget_show (scale_settings_rotate);
  gtk_box_pack_start (GTK_BOX (hbox3), scale_settings_rotate, TRUE, TRUE, 0);
  gtk_scale_set_value_pos (GTK_SCALE (scale_settings_rotate), GTK_POS_LEFT);
  gtk_scale_set_digits (GTK_SCALE (scale_settings_rotate), 0);

  label5 = gtk_label_new (_("<b>Settings</b>"));
  gtk_widget_show (label5);
  gtk_frame_set_label_widget (GTK_FRAME (frame2), label5);
  gtk_label_set_use_markup (GTK_LABEL (label5), TRUE);

  g_signal_connect ((gpointer) button_gallery_open, "clicked",
                    G_CALLBACK (on_button_gallery_open_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gallery_save, "clicked",
                    G_CALLBACK (on_button_gallery_save_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gallery_make, "clicked",
                    G_CALLBACK (on_button_gallery_make_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gallery_stop, "clicked",
                    G_CALLBACK (on_button_gallery_stop_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_gallery_configure, "clicked",
                    G_CALLBACK (on_button_gallery_configure_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_image_add, "clicked",
                    G_CALLBACK (on_button_image_add_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_image_remove, "clicked",
                    G_CALLBACK (on_button_image_remove_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_pwg_preferences, "clicked",
                    G_CALLBACK (on_button_pwg_preferences_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_pwg_quit, "clicked",
                    G_CALLBACK (on_button_pwg_quit_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_pwg_about, "clicked",
                    G_CALLBACK (on_button_pwg_about_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_move_top, "clicked",
                    G_CALLBACK (on_button_move_top_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_move_up, "clicked",
                    G_CALLBACK (on_button_move_up_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_move_down, "clicked",
                    G_CALLBACK (on_button_move_down_clicked),
                    NULL);
  g_signal_connect ((gpointer) button_move_bottom, "clicked",
                    G_CALLBACK (on_button_move_bottom_clicked),
                    NULL);
  g_signal_connect ((gpointer) check_settings_nomodify, "toggled",
                    G_CALLBACK (on_check_settings_nomodify_toggled),
                    NULL);
  g_signal_connect ((gpointer) scale_settings_gamma, "value_changed",
                    G_CALLBACK (on_scale_settings_gamma_value_changed),
                    NULL);
  g_signal_connect ((gpointer) scale_settings_rotate, "value_changed",
                    G_CALLBACK (on_scale_settings_rotate_value_changed),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, mainwindow, "mainwindow");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (mainwindow, button_gallery_open, "button_gallery_open");
  GLADE_HOOKUP_OBJECT (mainwindow, button_gallery_save, "button_gallery_save");
  GLADE_HOOKUP_OBJECT (mainwindow, button_gallery_make, "button_gallery_make");
  GLADE_HOOKUP_OBJECT (mainwindow, button_gallery_stop, "button_gallery_stop");
  GLADE_HOOKUP_OBJECT (mainwindow, button_gallery_configure, "button_gallery_configure");
  GLADE_HOOKUP_OBJECT (mainwindow, toolitem1, "toolitem1");
  GLADE_HOOKUP_OBJECT (mainwindow, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (mainwindow, button_image_add, "button_image_add");
  GLADE_HOOKUP_OBJECT (mainwindow, button_image_remove, "button_image_remove");
  GLADE_HOOKUP_OBJECT (mainwindow, toolitem2, "toolitem2");
  GLADE_HOOKUP_OBJECT (mainwindow, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (mainwindow, button_pwg_preferences, "button_pwg_preferences");
  GLADE_HOOKUP_OBJECT (mainwindow, button_pwg_quit, "button_pwg_quit");
  GLADE_HOOKUP_OBJECT (mainwindow, button_pwg_about, "button_pwg_about");
  GLADE_HOOKUP_OBJECT (mainwindow, hpaned1, "hpaned1");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox2, "vbox2");
  GLADE_HOOKUP_OBJECT (mainwindow, button_move_top, "button_move_top");
  GLADE_HOOKUP_OBJECT (mainwindow, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (mainwindow, image4, "image4");
  GLADE_HOOKUP_OBJECT (mainwindow, label8, "label8");
  GLADE_HOOKUP_OBJECT (mainwindow, button_move_up, "button_move_up");
  GLADE_HOOKUP_OBJECT (mainwindow, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (mainwindow, image2, "image2");
  GLADE_HOOKUP_OBJECT (mainwindow, label6, "label6");
  GLADE_HOOKUP_OBJECT (mainwindow, scrolledwindow_thumb, "scrolledwindow_thumb");
  GLADE_HOOKUP_OBJECT (mainwindow, table_thumb, "table_thumb");
  GLADE_HOOKUP_OBJECT (mainwindow, button_move_down, "button_move_down");
  GLADE_HOOKUP_OBJECT (mainwindow, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (mainwindow, image3, "image3");
  GLADE_HOOKUP_OBJECT (mainwindow, label7, "label7");
  GLADE_HOOKUP_OBJECT (mainwindow, button_move_bottom, "button_move_bottom");
  GLADE_HOOKUP_OBJECT (mainwindow, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (mainwindow, image5, "image5");
  GLADE_HOOKUP_OBJECT (mainwindow, label9, "label9");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox3, "vbox3");
  GLADE_HOOKUP_OBJECT (mainwindow, progressbar_status, "progressbar_status");
  GLADE_HOOKUP_OBJECT (mainwindow, label_filename, "label_filename");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (mainwindow, frame1, "frame1");
  GLADE_HOOKUP_OBJECT (mainwindow, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (mainwindow, scrolledwindow1, "scrolledwindow1");
  GLADE_HOOKUP_OBJECT (mainwindow, textview_description, "textview_description");
  GLADE_HOOKUP_OBJECT (mainwindow, label2, "label2");
  GLADE_HOOKUP_OBJECT (mainwindow, frame2, "frame2");
  GLADE_HOOKUP_OBJECT (mainwindow, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (mainwindow, vbox4, "vbox4");
  GLADE_HOOKUP_OBJECT (mainwindow, check_settings_nomodify, "check_settings_nomodify");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (mainwindow, label3, "label3");
  GLADE_HOOKUP_OBJECT (mainwindow, scale_settings_gamma, "scale_settings_gamma");
  GLADE_HOOKUP_OBJECT (mainwindow, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (mainwindow, label4, "label4");
  GLADE_HOOKUP_OBJECT (mainwindow, scale_settings_rotate, "scale_settings_rotate");
  GLADE_HOOKUP_OBJECT (mainwindow, label5, "label5");
  GLADE_HOOKUP_OBJECT_NO_REF (mainwindow, tooltips, "tooltips");

  return mainwindow;
}

GtkWidget*
create_aboutdialog (void)
{
  GtkWidget *aboutdialog;
  const gchar *authors[] = {
    "Tuomas Kulve",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator-credits");

  aboutdialog = gtk_about_dialog_new ();
  gtk_about_dialog_set_version (GTK_ABOUT_DIALOG (aboutdialog), VERSION);
  gtk_about_dialog_set_name (GTK_ABOUT_DIALOG (aboutdialog), _("pwgallery"));
  gtk_about_dialog_set_copyright (GTK_ABOUT_DIALOG (aboutdialog), _("Copyright Tuomas Kulve"));
  gtk_about_dialog_set_comments (GTK_ABOUT_DIALOG (aboutdialog), _("Web gallery generator"));
  gtk_about_dialog_set_license (GTK_ABOUT_DIALOG (aboutdialog), _("Copyright (C) 2006 Tuomas Kulve <tuomas@kulve.fi>\n\nThis program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2, or (at your option)any later version.\n\nThis program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more details.\n\nYou should have received a copy of the GNU General Public License along with this program; if not, write to the Free Software Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.\n"));
  gtk_about_dialog_set_wrap_license (GTK_ABOUT_DIALOG (aboutdialog), TRUE);
  gtk_about_dialog_set_website (GTK_ABOUT_DIALOG (aboutdialog), "http://tuomas.kulve.fi/projects/pwgallery");
  gtk_about_dialog_set_website_label (GTK_ABOUT_DIALOG (aboutdialog), _("Home page"));
  gtk_about_dialog_set_authors (GTK_ABOUT_DIALOG (aboutdialog), authors);
  gtk_about_dialog_set_translator_credits (GTK_ABOUT_DIALOG (aboutdialog), translators);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (aboutdialog, aboutdialog, "aboutdialog");

  return aboutdialog;
}

GtkWidget*
create_preferenceswindow (void)
{
  GtkWidget *preferenceswindow;
  GtkWidget *vbox5;
  GtkWidget *toolbar2;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *button_pref_save;
  GtkWidget *button_pref_cancel;
  GtkWidget *vbox6;
  GtkWidget *table5;
  GtkWidget *label10;
  GtkWidget *entry_pref_dir_img;
  GtkWidget *filechooserbutton1;
  GtkWidget *label11;
  GtkWidget *entry_pref_dir_gallery;
  GtkWidget *filechooserbutton2;
  GtkWidget *label12;
  GtkWidget *entry_pref_dir_template;
  GtkWidget *filechooserbutton3;
  GtkWidget *label13;
  GtkWidget *entry4;
  GtkWidget *filechooserbutton4;
  GtkWidget *label14;
  GtkWidget *entry5;
  GtkWidget *filechooserbutton5;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  preferenceswindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (preferenceswindow), _("Preferences"));
  gtk_window_set_modal (GTK_WINDOW (preferenceswindow), TRUE);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox5);
  gtk_container_add (GTK_CONTAINER (preferenceswindow), vbox5);

  toolbar2 = gtk_toolbar_new ();
  gtk_widget_show (toolbar2);
  gtk_box_pack_start (GTK_BOX (vbox5), toolbar2, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar2), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar2));

  tmp_image = gtk_image_new_from_stock ("gtk-save", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_pref_save = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Save"));
  gtk_widget_show (button_pref_save);
  gtk_container_add (GTK_CONTAINER (toolbar2), button_pref_save);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_pref_save), tooltips, _("Save preferences and close window"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-cancel", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_pref_cancel = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Cancel"));
  gtk_widget_show (button_pref_cancel);
  gtk_container_add (GTK_CONTAINER (toolbar2), button_pref_cancel);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_pref_cancel), tooltips, _("Discard changes"), NULL);

  vbox6 = gtk_vbox_new (TRUE, 0);
  gtk_widget_show (vbox6);
  gtk_box_pack_start (GTK_BOX (vbox5), vbox6, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox6), 10);

  table5 = gtk_table_new (5, 3, FALSE);
  gtk_widget_show (table5);
  gtk_box_pack_start (GTK_BOX (vbox6), table5, TRUE, TRUE, 0);

  label10 = gtk_label_new (_("Image directory: "));
  gtk_widget_show (label10);
  gtk_table_attach (GTK_TABLE (table5), label10, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label10), 0, 0.5);

  entry_pref_dir_img = gtk_entry_new ();
  gtk_widget_show (entry_pref_dir_img);
  gtk_table_attach (GTK_TABLE (table5), entry_pref_dir_img, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  filechooserbutton1 = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (filechooserbutton1);
  gtk_table_attach (GTK_TABLE (table5), filechooserbutton1, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  g_object_set (filechooserbutton1,
                "show-hidden", TRUE,
                NULL);

  label11 = gtk_label_new (_("Gallery directory: "));
  gtk_widget_show (label11);
  gtk_table_attach (GTK_TABLE (table5), label11, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label11), 0, 0.5);

  entry_pref_dir_gallery = gtk_entry_new ();
  gtk_widget_show (entry_pref_dir_gallery);
  gtk_table_attach (GTK_TABLE (table5), entry_pref_dir_gallery, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  filechooserbutton2 = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (filechooserbutton2);
  gtk_table_attach (GTK_TABLE (table5), filechooserbutton2, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  g_object_set (filechooserbutton2,
                "show-hidden", TRUE,
                NULL);

  label12 = gtk_label_new (_("Templates directory: "));
  gtk_widget_show (label12);
  gtk_table_attach (GTK_TABLE (table5), label12, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label12), 0, 0.5);

  entry_pref_dir_template = gtk_entry_new ();
  gtk_widget_show (entry_pref_dir_template);
  gtk_table_attach (GTK_TABLE (table5), entry_pref_dir_template, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  filechooserbutton3 = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (filechooserbutton3);
  gtk_table_attach (GTK_TABLE (table5), filechooserbutton3, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);
  g_object_set (filechooserbutton3,
                "show-hidden", TRUE,
                NULL);

  label13 = gtk_label_new (_("Default image template: "));
  gtk_widget_show (label13);
  gtk_table_attach (GTK_TABLE (table5), label13, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label13), 0, 0.5);

  entry4 = gtk_entry_new ();
  gtk_widget_show (entry4);
  gtk_table_attach (GTK_TABLE (table5), entry4, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  filechooserbutton4 = gtk_file_chooser_button_new (_("Select A File"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton4);
  gtk_table_attach (GTK_TABLE (table5), filechooserbutton4, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label14 = gtk_label_new (_("Default index template:"));
  gtk_widget_show (label14);
  gtk_table_attach (GTK_TABLE (table5), label14, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label14), 0, 0.5);

  entry5 = gtk_entry_new ();
  gtk_widget_show (entry5);
  gtk_table_attach (GTK_TABLE (table5), entry5, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  filechooserbutton5 = gtk_file_chooser_button_new (_("Select A File"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton5);
  gtk_table_attach (GTK_TABLE (table5), filechooserbutton5, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  g_signal_connect ((gpointer) button_pref_save, "clicked",
                    G_CALLBACK (on_button_pref_save_clicked),
                    NULL);
  g_signal_connect_swapped ((gpointer) button_pref_cancel, "clicked",
                            G_CALLBACK (gtk_widget_destroy),
                            GTK_OBJECT (preferenceswindow));

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (preferenceswindow, preferenceswindow, "preferenceswindow");
  GLADE_HOOKUP_OBJECT (preferenceswindow, vbox5, "vbox5");
  GLADE_HOOKUP_OBJECT (preferenceswindow, toolbar2, "toolbar2");
  GLADE_HOOKUP_OBJECT (preferenceswindow, button_pref_save, "button_pref_save");
  GLADE_HOOKUP_OBJECT (preferenceswindow, button_pref_cancel, "button_pref_cancel");
  GLADE_HOOKUP_OBJECT (preferenceswindow, vbox6, "vbox6");
  GLADE_HOOKUP_OBJECT (preferenceswindow, table5, "table5");
  GLADE_HOOKUP_OBJECT (preferenceswindow, label10, "label10");
  GLADE_HOOKUP_OBJECT (preferenceswindow, entry_pref_dir_img, "entry_pref_dir_img");
  GLADE_HOOKUP_OBJECT (preferenceswindow, filechooserbutton1, "filechooserbutton1");
  GLADE_HOOKUP_OBJECT (preferenceswindow, label11, "label11");
  GLADE_HOOKUP_OBJECT (preferenceswindow, entry_pref_dir_gallery, "entry_pref_dir_gallery");
  GLADE_HOOKUP_OBJECT (preferenceswindow, filechooserbutton2, "filechooserbutton2");
  GLADE_HOOKUP_OBJECT (preferenceswindow, label12, "label12");
  GLADE_HOOKUP_OBJECT (preferenceswindow, entry_pref_dir_template, "entry_pref_dir_template");
  GLADE_HOOKUP_OBJECT (preferenceswindow, filechooserbutton3, "filechooserbutton3");
  GLADE_HOOKUP_OBJECT (preferenceswindow, label13, "label13");
  GLADE_HOOKUP_OBJECT (preferenceswindow, entry4, "entry4");
  GLADE_HOOKUP_OBJECT (preferenceswindow, filechooserbutton4, "filechooserbutton4");
  GLADE_HOOKUP_OBJECT (preferenceswindow, label14, "label14");
  GLADE_HOOKUP_OBJECT (preferenceswindow, entry5, "entry5");
  GLADE_HOOKUP_OBJECT (preferenceswindow, filechooserbutton5, "filechooserbutton5");
  GLADE_HOOKUP_OBJECT_NO_REF (preferenceswindow, tooltips, "tooltips");

  return preferenceswindow;
}

GtkWidget*
create_gallerywindow (void)
{
  GtkWidget *gallerywindow;
  GtkWidget *vbox7;
  GtkWidget *toolbar3;
  GtkIconSize tmp_toolbar_icon_size;
  GtkWidget *tmp_image;
  GtkWidget *toolbutton_gal_save;
  GtkWidget *button_gal_cancel;
  GtkWidget *table4;
  GtkWidget *label15;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *label18;
  GtkWidget *label19;
  GtkWidget *entry_gal_name;
  GtkWidget *entry_gal_destdir;
  GtkWidget *entry_gal_index_templ;
  GtkWidget *entry_gal_img_templ;
  GtkWidget *filechooserbutton7;
  GtkWidget *filechooserbutton9;
  GtkWidget *filechooserbutton10;
  GtkWidget *label20;
  GtkWidget *togglebutton_gal_hideexif;
  GtkWidget *alignment7;
  GtkWidget *hbox18;
  GtkWidget *image6;
  GtkWidget *label21;
  GtkWidget *label22;
  GtkObject *spinbutton_gal_thumb_w_adj;
  GtkWidget *spinbutton_gal_thumb_w;
  GtkObject *spinbutton_gal_image_h_adj;
  GtkWidget *spinbutton_gal_image_h;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  gallerywindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gallerywindow), _("Gallery settings"));
  gtk_window_set_modal (GTK_WINDOW (gallerywindow), TRUE);

  vbox7 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox7);
  gtk_container_add (GTK_CONTAINER (gallerywindow), vbox7);

  toolbar3 = gtk_toolbar_new ();
  gtk_widget_show (toolbar3);
  gtk_box_pack_start (GTK_BOX (vbox7), toolbar3, FALSE, FALSE, 0);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar3), GTK_TOOLBAR_BOTH);
  tmp_toolbar_icon_size = gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar3));

  tmp_image = gtk_image_new_from_stock ("gtk-save", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  toolbutton_gal_save = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Save"));
  gtk_widget_show (toolbutton_gal_save);
  gtk_container_add (GTK_CONTAINER (toolbar3), toolbutton_gal_save);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (toolbutton_gal_save), tooltips, _("Save settings and close"), NULL);

  tmp_image = gtk_image_new_from_stock ("gtk-cancel", tmp_toolbar_icon_size);
  gtk_widget_show (tmp_image);
  button_gal_cancel = (GtkWidget*) gtk_tool_button_new (tmp_image, _("Cancel"));
  gtk_widget_show (button_gal_cancel);
  gtk_container_add (GTK_CONTAINER (toolbar3), button_gal_cancel);
  gtk_tool_item_set_tooltip (GTK_TOOL_ITEM (button_gal_cancel), tooltips, _("Discard changes"), NULL);

  table4 = gtk_table_new (7, 3, FALSE);
  gtk_widget_show (table4);
  gtk_box_pack_start (GTK_BOX (vbox7), table4, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (table4), 5);

  label15 = gtk_label_new (_("Name of the gallery: "));
  gtk_widget_show (label15);
  gtk_table_attach (GTK_TABLE (table4), label15, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label15), 0, 0.5);

  label16 = gtk_label_new (_("Destination directory: "));
  gtk_widget_show (label16);
  gtk_table_attach (GTK_TABLE (table4), label16, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label16), 0, 0.5);

  label17 = gtk_label_new (_("Thumbnail width: "));
  gtk_widget_show (label17);
  gtk_table_attach (GTK_TABLE (table4), label17, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label17), 0, 0.5);

  label18 = gtk_label_new (_("Index template: "));
  gtk_widget_show (label18);
  gtk_table_attach (GTK_TABLE (table4), label18, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label18), 0, 0.5);

  label19 = gtk_label_new (_("Image template: "));
  gtk_widget_show (label19);
  gtk_table_attach (GTK_TABLE (table4), label19, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label19), 0, 0.5);

  entry_gal_name = gtk_entry_new ();
  gtk_widget_show (entry_gal_name);
  gtk_table_attach (GTK_TABLE (table4), entry_gal_name, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_gal_destdir = gtk_entry_new ();
  gtk_widget_show (entry_gal_destdir);
  gtk_table_attach (GTK_TABLE (table4), entry_gal_destdir, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_gal_index_templ = gtk_entry_new ();
  gtk_widget_show (entry_gal_index_templ);
  gtk_table_attach (GTK_TABLE (table4), entry_gal_index_templ, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  entry_gal_img_templ = gtk_entry_new ();
  gtk_widget_show (entry_gal_img_templ);
  gtk_table_attach (GTK_TABLE (table4), entry_gal_img_templ, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  filechooserbutton7 = gtk_file_chooser_button_new (_("Select A Folder"), GTK_FILE_CHOOSER_ACTION_SELECT_FOLDER);
  gtk_widget_show (filechooserbutton7);
  gtk_table_attach (GTK_TABLE (table4), filechooserbutton7, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  filechooserbutton9 = gtk_file_chooser_button_new (_("Select A File"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton9);
  gtk_table_attach (GTK_TABLE (table4), filechooserbutton9, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  filechooserbutton10 = gtk_file_chooser_button_new (_("Select A File"), GTK_FILE_CHOOSER_ACTION_OPEN);
  gtk_widget_show (filechooserbutton10);
  gtk_table_attach (GTK_TABLE (table4), filechooserbutton10, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (GTK_FILL), 0, 0);

  label20 = gtk_label_new (_("Exif-data: "));
  gtk_widget_show (label20);
  gtk_table_attach (GTK_TABLE (table4), label20, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label20), 0, 0.5);

  togglebutton_gal_hideexif = gtk_toggle_button_new ();
  gtk_widget_show (togglebutton_gal_hideexif);
  gtk_table_attach (GTK_TABLE (table4), togglebutton_gal_hideexif, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (togglebutton_gal_hideexif), alignment7);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox18);

  image6 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox18), image6, FALSE, FALSE, 0);

  label21 = gtk_label_new_with_mnemonic (_("Hide"));
  gtk_widget_show (label21);
  gtk_box_pack_start (GTK_BOX (hbox18), label21, FALSE, FALSE, 0);

  label22 = gtk_label_new (_("Image height: "));
  gtk_widget_show (label22);
  gtk_table_attach (GTK_TABLE (table4), label22, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (label22), 0, 0.5);

  spinbutton_gal_thumb_w_adj = gtk_adjustment_new (0, 0, 10000, 1, 10, 10);
  spinbutton_gal_thumb_w = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_gal_thumb_w_adj), 1, 0);
  gtk_widget_show (spinbutton_gal_thumb_w);
  gtk_table_attach (GTK_TABLE (table4), spinbutton_gal_thumb_w, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  spinbutton_gal_image_h_adj = gtk_adjustment_new (1, 0, 10000, 1, 10, 10);
  spinbutton_gal_image_h = gtk_spin_button_new (GTK_ADJUSTMENT (spinbutton_gal_image_h_adj), 1, 0);
  gtk_widget_show (spinbutton_gal_image_h);
  gtk_table_attach (GTK_TABLE (table4), spinbutton_gal_image_h, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gallerywindow, gallerywindow, "gallerywindow");
  GLADE_HOOKUP_OBJECT (gallerywindow, vbox7, "vbox7");
  GLADE_HOOKUP_OBJECT (gallerywindow, toolbar3, "toolbar3");
  GLADE_HOOKUP_OBJECT (gallerywindow, toolbutton_gal_save, "toolbutton_gal_save");
  GLADE_HOOKUP_OBJECT (gallerywindow, button_gal_cancel, "button_gal_cancel");
  GLADE_HOOKUP_OBJECT (gallerywindow, table4, "table4");
  GLADE_HOOKUP_OBJECT (gallerywindow, label15, "label15");
  GLADE_HOOKUP_OBJECT (gallerywindow, label16, "label16");
  GLADE_HOOKUP_OBJECT (gallerywindow, label17, "label17");
  GLADE_HOOKUP_OBJECT (gallerywindow, label18, "label18");
  GLADE_HOOKUP_OBJECT (gallerywindow, label19, "label19");
  GLADE_HOOKUP_OBJECT (gallerywindow, entry_gal_name, "entry_gal_name");
  GLADE_HOOKUP_OBJECT (gallerywindow, entry_gal_destdir, "entry_gal_destdir");
  GLADE_HOOKUP_OBJECT (gallerywindow, entry_gal_index_templ, "entry_gal_index_templ");
  GLADE_HOOKUP_OBJECT (gallerywindow, entry_gal_img_templ, "entry_gal_img_templ");
  GLADE_HOOKUP_OBJECT (gallerywindow, filechooserbutton7, "filechooserbutton7");
  GLADE_HOOKUP_OBJECT (gallerywindow, filechooserbutton9, "filechooserbutton9");
  GLADE_HOOKUP_OBJECT (gallerywindow, filechooserbutton10, "filechooserbutton10");
  GLADE_HOOKUP_OBJECT (gallerywindow, label20, "label20");
  GLADE_HOOKUP_OBJECT (gallerywindow, togglebutton_gal_hideexif, "togglebutton_gal_hideexif");
  GLADE_HOOKUP_OBJECT (gallerywindow, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (gallerywindow, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (gallerywindow, image6, "image6");
  GLADE_HOOKUP_OBJECT (gallerywindow, label21, "label21");
  GLADE_HOOKUP_OBJECT (gallerywindow, label22, "label22");
  GLADE_HOOKUP_OBJECT (gallerywindow, spinbutton_gal_thumb_w, "spinbutton_gal_thumb_w");
  GLADE_HOOKUP_OBJECT (gallerywindow, spinbutton_gal_image_h, "spinbutton_gal_image_h");
  GLADE_HOOKUP_OBJECT_NO_REF (gallerywindow, tooltips, "tooltips");

  return gallerywindow;
}

