/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_mainwindow (void);
GtkWidget* create_aboutdialog (void);
GtkWidget* create_preferenceswindow (void);
GtkWidget* create_gallerywindow (void);
